final Map<String, String> cryptoPairs = {
  'BTCtoUSD': 'Bitcoin to US Dollar',
  'ETHtoUSD': 'Ethereum to US Dollar',
  'XRPtoUSD': 'Ripple to US Dollar',
  'LTCtoUSD': 'Litecoin to US Dollar',
  'BCHtoUSD': 'Bitcoin Cash to US Dollar',
  'ADAtoUSD': 'Cardano to US Dollar',
  'DOTtoUSD': 'Polkadot to US Dollar',
  'BNBtoUSD': 'Binance Coin to US Dollar',
  'LINKtoUSD': 'Chainlink to US Dollar',
  'XMRtoUSD': 'Monero to US Dollar',
  'USDCtoUSD': 'USD Coin to US Dollar',
  'DOGEtoUSD': 'Dogecoin to US Dollar',
  'UNItoUSD': 'Uniswap to US Dollar',
  'ATOMtoUSD': 'Cosmos to US Dollar',
  'XLMtoUSD': 'Stellar to US Dollar',
  'WBTCtoUSD': 'Wrapped Bitcoin to US Dollar',
  'FILtoUSD': 'Filecoin to US Dollar',
  'AAVEtoUSD': 'Aave to US Dollar',
  'TRXtoUSD': 'TRON to US Dollar',
  'XTZtoUSD': 'Tezos to US Dollar',
  'EOStoUSD': 'EOS to US Dollar',
  'COMPtoUSD': 'Compound to US Dollar',
  'MKRtoUSD': 'Maker to US Dollar',
  'SNXtoUSD': 'Synthetix to US Dollar',
  'DASHtoUSD': 'Dash to US Dollar',
  'ZECtoUSD': 'Zcash to US Dollar',
  'VETtoUSD': 'VeChain to US Dollar',
  'ICXtoUSD': 'ICON to US Dollar',
  'NEOtoUSD': 'NEO to US Dollar',
  'EGLDtoUSD': 'EagleCoin to US Dollar',
  'ALGOtoUSD': 'Algorand to US Dollar',
  'DGBtoUSD': 'DigiByte to US Dollar',
  'ONTtoUSD': 'Ontology to US Dollar',
  // Add more pairs as needed
};
